/**
 * Patient model — represents a patient record.
 *
 * Two types:
 *   - "lab"       → Outpatient. Comes for lab tests only. No seat assigned.
 *   - "inpatient" → Admitted. Has a seat, guardian info, admission date.
 *
 * The patientId field (PT-YYYY-NNNNN) is auto-generated by the service layer.
 * Phone is NOT unique because family members often share one phone number.
 */
const mongoose = require("mongoose");
const { PATIENT_TYPES, PATIENT_STATUSES, GENDERS } = require("../utils/constants");

const patientSchema = new mongoose.Schema(
  {
    patientId: {
      type: String,
      required: [true, "Patient ID is required"],
      unique: true,
      trim: true,
    },
    name: {
      type: String,
      required: [true, "Patient name is required"],
      trim: true,
    },
    age: {
      type: Number,
      required: [true, "Age is required"],
      min: [0, "Age cannot be negative"],
    },
    gender: {
      type: String,
      required: [true, "Gender is required"],
      enum: GENDERS,
    },
    phone: {
      type: String,
      required: [true, "Phone number is required"],
      trim: true,
      // NOTE: NOT unique — multiple patients can share the same phone
    },
    address: { type: String, default: "", trim: true },
    type: {
      type: String,
      enum: PATIENT_TYPES,
      default: "lab",
    },
    admissionDate: { type: Date, default: null },
    seatId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Seat",
      default: null,
    },
    roomName: { type: String, default: null },
    bedName: { type: String, default: null },
    guardianName: { type: String, default: null, trim: true },
    guardianPhone: { type: String, default: null, trim: true },
    emergencyContact: { type: String, default: null, trim: true },
    referenceDoctor: { type: String, default: null, trim: true },
    status: {
      type: String,
      enum: PATIENT_STATUSES,
      default: "active",
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

// Index for fast phone lookups (not unique)
patientSchema.index({ phone: 1 });
patientSchema.index({ type: 1, status: 1, createdAt: -1 });
patientSchema.index({ createdAt: -1 });

module.exports = mongoose.model("Patient", patientSchema);
